sensor:
  - platform: adc
    id: ${node_name}_batterysensor
    pin: ${battery_pin}
    name: Battery ${visible_name}
    device_class: "voltage"
    update_interval: never
    filters:
    # - median:
        # window_size: ${probes_count}
        # send_every: ${probes_count}-1
        # send_first_at: ${probes_count}-1
    - lambda: if (x < 1) return 0; else return (x);
    accuracy_decimals: 2

script:
  - id: battery_update
    then:
      - component.update: ${node_name}_batterysensor
      - logger.log:
          format: "Updated battery sensor value %.1f, raw value %.3f"
          args: [ 'id(${node_name}_batterysensor).state', 'id(${node_name}_batterysensor).raw_state' ]