substitutions:
  node_name: hsensor
  visible_name: HSensor
  battery_pin: "34"
  power_sensors_pin: GPIO32

packages:
  device_base: !include common.yaml
# used scripts: 
#   controlled_sleep
  battery: !include battery.yaml
# used scripts:
#   battery_update


script: 
  - id: main_script # required, as it will be called on boot
    then:
      - script.execute: read_all_and_sleep
      
  - id: read_sensors_script
    then:
      - output.turn_on: power_sensors
      - delay: 500ms
      - component.update: soilsensor
      - script.execute: battery_update
      - output.turn_off: power_sensors
      - logger.log:
          format: "Updated soil sensor %.1f, raw value %.3f"
          args: [ 'id(soilsensor).state', 'id(soilsensor).raw_state' ]
      - delay: 3s
      
  - id: read_all_and_sleep
    then:
      - script.execute: read_sensors_script
      - script.wait: read_sensors_script
      - delay: 10s
      - script.execute: controlled_sleep


sensor:
  - platform: adc
    id: soilsensor
    pin: 33
    name: "Soil Moisture"
    device_class: "humidity"
    update_interval: never
    unit_of_measurement: "%"
    attenuation: 12db
#    samples: ${probes_count} // Multisampling not yet in release as of 16.05.24, hence need median block below
    filters:
    # - median:
        # window_size: ${probes_count}
        # send_every: ${probes_count}-1
        # send_first_at: ${probes_count}-1
    - calibrate_linear:
        - 0.85 -> 0.00
        - 0.44 -> 100.00
    - lambda: if (x < 1) return 0; else return (x);
    accuracy_decimals: 1
    
output:
  - platform: gpio
    pin: ${power_sensors_pin}
    id: power_sensors


